@startuml
!define PRIMARY_KEY(x) <u>x</u>
!define FOREIGN_KEY(x) #x

class users {
    PRIMARY_KEY(id : Integer)
    login : String(256)
    first_name : String(256)
    last_name : String(256)
    email : String(256)
}

class services {
    PRIMARY_KEY(id : Integer)
    name : String(256)
    description : TEXT
    cost : DECIMAL(10, 2)
}

class orders {
    PRIMARY_KEY(id : Integer)
    FOREIGN_KEY(user_id : Integer)
    date_created : DateTime
}

class order_service {
    FOREIGN_KEY(order_id : Integer)
    FOREIGN_KEY(service_id : Integer)
}

users "1" -- "0..*" Order : has >
orders "0..*" -- "0..*" order_service : uses >
services "0..*" -- "0..*" order_service : offers >
order_service -- orders
order_service -- services

@enduml
