@startuml
!define PRIMARY_KEY(x) <u>x</u>
!define FOREIGN_KEY(x) #x

class User {
    PRIMARY_KEY(id : Integer)
    login : String(256)
    first_name : String(256)
    last_name : String(256)
    email : String(256)
}

class Service {
    PRIMARY_KEY(id : Integer)
    name : String(256)
    description : TEXT
    cost : DECIMAL(10, 2)
}

class Order {
    PRIMARY_KEY(id : Integer)
    FOREIGN_KEY(user_id : Integer)
    date_created : DateTime
}

class order_service {
    FOREIGN_KEY(order_id : Integer)
    FOREIGN_KEY(service_id : Integer)
}

User "1" -- "0..*" Order : has >
Order "0..*" -- "0..*" order_service : uses >
Service "0..*" -- "0..*" order_service : offers >
order_service -- Order
order_service -- Service

@enduml
